### ISSUE TITLE
Image Uploader/Picker Component for avatar/logo of the backers/sponsors

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/website#122]
Right now, we are using [Clearbit](http://clearbit.com) to automatically try to pull the avatar based on the email address of a new donor.

We should give people the option to upload/pick their avatar.

It would be great to have an ImagePicker React Component

    <ImagePicker 
      twitter="xdamman" 
      email="xdamman@..." 
      website="https://xdamman.com" 
      src=":currentAvatarURLIfAny"
      className="avatar" // (or "logo")
    />

Alternatively, we could have an API call to retrieve the different possible values for `imageUrl` given an `email`, `website`, `twitter` and have a more generic `ImagePicker` component that would just accept an array of images to choose from with a default index.

    <ImagePicker
      src="url1,url2,url3"
      default=0 // index of the default image
      allowUpload=true
    />

And on API:

    GET /images?email=:email&twitter=:twitter&website=:website

Which would return something like

    [
      {
        source: "twitter",
        src: "url",
        width: "120px", // if we know the width
        height: "100px"
      },
      {
        source: "xdamman.com",
        src: "url"
      }
    ]

The frontend design should be a rectangle (className=logo) or a round (className=avatar) with a left and right arrow to skim through the possible values (with dots at the bottom to indicate the position). The last position should be an Upload Icon that lets the user upload or drag'n'drop an image.

Thoughts?

**Comment by carlosascari** [comment]
I like the API approach, its much more flexible, besides avatars that it can find, based on a backer's information, it can also provide a set of presets to choose from as well, in case the user does not provide twitter/website info. 

Dario had in mind, to choose from a random set of avatars, for those who have an empty avatar, this is so you don't see the same stub image. 

All in all: API that returns a set of random preset images,  and if possible, twitter and facebook images.

**Comment by carlosascari** [comment]
Im taking this issue

**Comment by xdamman** [comment]
Fixed in https://github.com/OpenCollective/website/pull/128
