### ISSUE TITLE
List of backers: doesn't work when backer is called 'member'

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/website#201]
See https://opencollective.com/ConsciousnessHackingSF

Related to https://github.com/OpenCollective/website/pull/195

The way to solve this is to go through the `group.tiers` array and for each `tier.name`, count the number of members. And then order them by `tier.range[0]` in ascending order.

**Comment by carlosascari** [comment]
@xdamman Why do I need to order them, if all that is needed the length/count?

Would this not be enough?:
```
const memberCount = filterCollection(group.tiers, {name: 'member'}).length;
```
Then we'd add it to backerCount

**Comment by xdamman** [comment]
No because you can't make any assumption on the name of the tier. It could be contributor, member, sponsor, supporter, etc... It's up to the collective.
So you need to circle through all the tiers and for each find out how many members and then show:
"We have X tier1.name, Y tier2.name and Z tier3.name"
where, X, Y and Z are in descending order.

**Comment by carlosascari** [comment]
@xdamman i've made a PR with the fixes please review

https://github.com/OpenCollective/website/pull/205

**Comment by xdamman** [comment]
Fixed and deployed.
Thanks @carlosascari!
