### ISSUE TITLE
404 on a number of redirects in /opensource

### ISSUE THREAD

**Issue by medied** [OpenCollective/website#218]
Ran into a few 404s (awesome gif, by the way) in [/opensource](https://opencollective.com/opensource) when clicking on some of the Open Source Collective members. Specifically for the following:

https://opencollective.com/opencollective.com/mochajs
https://opencollective.com/opencollective.com/yeoman
https://opencollective.com/opencollective.com/angular-fullstack
https://opencollective.com/opencollective.com/gulpjs

Looking at `UserCard.js`, it seems the `user.website` property may be faulty for some of the members? 

```javascript
  render() {
    const { className = '', user, i18n } = this.props;
    
    const twitterUrl = (user.twitterHandle) ? `https://twitter.com/${user.twitterHandle}` : '';
    const href = (user.website || twitterUrl);

    const roleLabel = (user.tier || user.role).toLowerCase();
    const addBadge = (roleLabel !== 'sponsor' && roleLabel !== 'member');

    return (
      <article className={`UserCard bg-white pt3 ${className} ${user.tier}`}>
        {this._link(href, <UserPhoto user={user} addBadge={addBadge} className='mx-auto' />)}
        <p className='UserCard-name PublicGroup-font-15 h5 my2 px2 -ff-sec'>{this._link(href, user.name)}</p>
        <div className='border-top border-gray px3 py2'>
          <p className='UserCard-role m0 -green -fw-bold -ttu'>{i18n.getString(roleLabel)}</p>
          <p className='h6 muted m0'>{i18n.getString('since')} {i18n.moment(user.createdAt).format('MMMM YYYY')}</p>
        </div>
      </article>
    );
  }
}
```

**Comment by asood123** [comment]
Good catch. Fixed.

**Comment by medied** [comment]
Nice. Looks like GulpJS is still missing though - https://opencollective.com/opencollective.com/gulpjs

**Comment by piamancini** [comment]
fixed, thanks!
